---
title: "data_exploration"
output:
  html_document: default
  pdf_document: default
---

```{r}
# install.packages("rmarkdown")
# install.packages("readr")
library(readr)
```

## Loading and cleaning dataset

```{r, message=FALSE, warning=FALSE}
# Loading and cleaning data from source

col_names <- c('country', 'year', 'status', 'life_expectancy', 'adult_mortality', 
               'infant_deaths', 'alcohol', 'percent_expend', 'hep_b', 'measles', 
               'bmi', 'deaths_under5', 'polio', 'total_expend', 'diptheria', 'hiv_aids', 
               'gdp', 'population', 'thin_1_19', 'thin_5_9', 'income_comp', 'schooling')

data <- read_csv('data/life_expectancy_raw.csv', 
                 col_names = col_names, 
                 col_types = cols(population = col_double()), 
                 trim_ws = TRUE)

head(data, 10) #view first 10 rows
```
### Data exploration and scoping

```{r, message=FALSE, warning=FALSE}

# Picking data from one year- try most recent year

data_2015 = data[data$year == 2015, ] # Most recent year available

missing_2015 <- colSums(is.na(data_2015))
print("Columns with more than 10% missing data for 2015:")
print(missing_2015[missing_2015 > 18])

# Two predictors with data mostly incomplete- try the next most recent year

data_2014 = data[data$year == 2014, ] # Next most recent year
missing_2014 <- colSums(is.na(data_2014))
print("Columns with more than 10% missing data for 2014:")
print(missing_2014[missing_2014 > 18])


```
```{r, message=FALSE, warning=FALSE}

# clean out 2014 data with complete columns to use as input for analysis

input <- data_2014[complete.cases(data_2014), ]

# convert country status to numerical dummy variable
input["status_code"] <- NA
input$status_code[input$status == 'Developed'] <- 1
input$status_code[input$status == 'Developing'] <- 0

# drop unused columns for regression model
input <- input[, !(colnames(input) %in% c('country', 'year', 'status'))]

head(input, 10) #view first 10 rows
write.csv(input, file='data/life_expectancy_input.csv')
```

## TO-DO

### List of variables

